#!/home/vukw/anaconda3/envs/env39_gandlf_dp/bin/python
# -*- coding: utf-8 -*-
import re
import sys
from GANDLF.entrypoints.cli_tool import gandlf
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(gandlf())
