version:
  maximum: 0.0.20
  minimum: 0.0.18
model:
  architecture: resnet18
  dimension: 2
  final_layer: softmax
  n_channels: 3
  class_list: [0, 1]
nested_training:
  testing: 1
  validation: 2
loss_function: cel
batch_size: 4
metrics:
- classification_accuracy
- f1
num_epochs: 20
q_verbose: true
patch_size:
- 160
- 160
modality: rad
track_memory_usage: true
memory_save_mode: true
learning_rate: 0.0001
scheduler:
  type: cosineannealing
  min_lr: 0.00001
differential_privacy: false
data_preprocessing:
  resize_image:
  - 160
  - 160
