version:
  maximum: 0.1.1
  minimum: 0.0.18
model:
  architecture: imagenet_vgg11
  dimension: 2
  final_layer: softmax
  norm_type: instance
  n_channels: 3
  class_list: [0, 1, 2]
  pretrained: true
nested_training:
  testing: 1
  validation: 2
loss_function: cel
batch_size: 2
metrics:
- classification_accuracy
- f1
num_epochs: 200
q_verbose: true
patch_size:
- 160
- 160
modality: rad
track_memory_usage: true
memory_save_mode: true
learning_rate: 0.000001
opt: sgd
q_samples_per_volume: 4
differential_privacy:
  max_grad_norm: 1000000.0
  noise_multiplier: 0.000000001
data_preprocessing:
  resize_image: [160, 160]
